In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

In [2]:
df = pd.read_csv('../data/fully combined/wr_all_weeks.csv')
print(f'Shape: {df.shape}')
print(f'Sezone: {df["season"].min()} – {df["season"].max()}')
df.head()

Shape: (46115, 99)
Sezone: 2015 – 2025

,game_id,receiver_player_id,receiver_player_name,passer_player_id,defteam,targets,receptions,receiving_yards,air_yards,yac,tds,epa,wpa,avg_depth,catch_rate,posteam,team_pass_attempts,team_air_yards,team_epa,air_yard_share,target_share,yards_per_target,def_targets_dev,def_receptions_dev,def_yards_dev,...,targets_Q4,lost_yards_due_to_penalty,yards_wp_<25,yards_wp_25_45,yards_wp_45_55,yards_wp_55_75,yards_wp_>75,yards_wp_NA,receptions_wp_<25,receptions_wp_25_45,receptions_wp_45_55,receptions_wp_55_75,receptions_wp_>75,receptions_wp_NA,targets_wp_<25,targets_wp_25_45,targets_wp_45_55,targets_wp_55_75,targets_wp_>75,targets_wp_NA,home_team,away_team,pregame_spread,pregame_total,season
0,2015_01_BAL_DEN,00-0020337,S.Smith,00-0026158,10,7.0,2.0,13.0,60.0,7.0,0.0,-10.770362,-0.462443,8.571429,0.285714,3,32.0,192.0,-13.765043,0.312500,0.21875,1.857143,1.044305,0.967226,0.904681,...,3.0,0.0,0.0,13.0,0.0,0.0,0.0,0,0.0,2.0,0.0,0.0,0.0,0,0,5,0,2,0,0,10,3,4.5,46.5,2015
1,2015_01_BAL_DEN,00-0024313,O.Daniels,00-0010346,3,2.0,2.0,5.0,2.0,3.0,0.0,-0.248920,-0.006820,1.000000,1.000000,3,32.0,192.0,-13.765043,0.010417,0.06250,2.500000,0.959631,0.973374,0.957703,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0,0.0,0.0,0.0,0.0,2.0,0,0,0,0,0,2,0,10,3,4.5,46.5,2015
2,2015_01_BAL_DEN,00-0026237,A.Caldwell,00-0010346,3,1.0,1.0,1.0,0.0,1.0,0.0,-0.664543,-0.022189,0.000000,1.000000,3,32.0,192.0,-13.765043,0.000000,0.03125,1.000000,0.959631,0.973374,0.957703,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.0,0.0,0.0,1.0,0,0,0,0,0,1,0,10,3,4.5,46.5,2015
3,2015_01_BAL_DEN,00-0026373,J.Forsett,00-0026158,10,7.0,4.0,13.0,5.0,13.0,0.0,-1.504406,-0.141163,0.714286,0.571429,3,32.0,192.0,-13.765043,0.026042,0.21875,1.857143,1.044305,0.967226,0.904681,...,3.0,0.0,6.0,0.0,0.0,7.0,0.0,0,3.0,0.0,0.0,1.0,0.0,0,4,2,0,1,0,0,10,3,4.5,46.5,2015
4,2015_01_BAL_DEN,00-0026739,J.Norwood,00-0010346,3,5.0,2.0,25.0,50.0,7.0,0.0,-5.110127,-0.168977,10.000000,0.400000,3,32.0,192.0,-13.765043,0.260417,0.15625,5.000000,0.959631,0.973374,0.957703,...,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0,0.0,0.0,0.0,2.0,0.0,0,0,0,0,2,3,0,10,3,4.5,46.5,2015

In [38]:
df.dtypes.to_frame('dtype').reset_index().rename(columns={'index': 'column'})

                  column    dtype
0                game_id   object
1     receiver_player_id   object
2   receiver_player_name   object
3       passer_player_id   object
4                defteam    int64
..                   ...      ...
94             home_team    int64
95             away_team    int64
96        pregame_spread  float64
97         pregame_total  float64
98                season    int64

[99 rows x 2 columns]

In [39]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)
pd.DataFrame({'missing_count': missing, 'missing_pct': missing_pct})

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

In [40]:
df.describe().T

                   count         mean        std     min     25%     50%     75%     max
defteam          46115.0    15.965998   9.628853     0.0     8.0    16.0    25.0    32.0
targets          46115.0     4.020362   3.131419     1.0     1.0     3.0     6.0    23.0
receptions       46115.0     2.656554   2.268011     0.0     1.0     2.0     4.0    18.0
receiving_yards  46115.0    29.642047  31.758577   -17.0     7.0    19.0    43.0   300.0
air_yards        46115.0    32.209845  40.914385   -92.0     3.0    17.0    50.0   334.0
...                  ...          ...        ...     ...     ...     ...     ...     ...
home_team        46115.0    15.959861   9.619081     0.0     8.0    16.0    25.0    32.0
away_team        46115.0    15.971831   9.620773     0.0     8.0    16.0    24.0    32.0
pregame_spread   46115.0     1.890914   5.962851   -18.0    -3.0     3.0     6.0    22.0
pregame_total    46115.0    45.339640   4.338047    28.5    42.5    45.0    48.0    63.5
season           46115.0  2019.789288   3.013629  2015.0  2017.0  2020.0  2022.0  2025.0

[95 rows x 8 columns]

In [41]:
df.groupby('season').size().rename('zapisi').reset_index()

    season  zapisi
0     2015    4314
1     2016    4308
2     2017    4332
3     2018    4304
4     2019    4274
5     2020    4435
6     2021    4616
7     2022    4550
8     2023    4599
9     2024    4465
10    2025    1918

In [3]:
df['week'] = df['game_id'].str.split('_').str[1].astype(int)
df = df.sort_values(['receiver_player_id', 'season', 'week'], ascending=[True, True, True]).reset_index(drop=True)

print('Tjedni:', sorted(df['week'].unique()))
df.groupby('week').size().rename('zapisi').reset_index()

Tjedni: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

    week  zapisi
0      1    2780
1      2    2826
2      3    2820
3      4    2748
4      5    2566
5      6    2542
6      7    2536
7      8    2569
8      9    2219
9     10    2224
10    11    2269
11    12    2474
12    13    2450
13    14    2436
14    15    2588
15    16    2598
16    17    2555
17    18    1421
18    19     765
19    20     448
20    21     214
21    22      67

In [4]:
df['weeks_since_last_game'] = (
    df.groupby(['receiver_player_id', 'season'])['week']
      .diff()
      .fillna(1)
      .clip(lower=1)
      .astype(int)
)

print(df['weeks_since_last_game'].value_counts().sort_index().head(10))
df[['receiver_player_id', 'season', 'week', 'weeks_since_last_game']].head(20)

weeks_since_last_game
1     37174
2      5324
3      1535
4       776
5       463
6       280
7       196
8       114
9        85
10       61
Name: count, dtype: int64

   receiver_player_id  season  week  weeks_since_last_game
0          00-0019596    2015    13                      1
1          00-0019596    2017    21                      1
2          00-0019596    2018    10                      1
3          00-0019596    2022    10                      1
4          00-0020337    2015     1                      1
5          00-0020337    2015     2                      1
6          00-0020337    2015     3                      1
7          00-0020337    2015     4                      1
8          00-0020337    2015     6                      2
9          00-0020337    2015     7                      1
10         00-0020337    2015     8                      1
11         00-0020337    2016     1                      1
12         00-0020337    2016     2                      1
13         00-0020337    2016     3                      1
14         00-0020337    2016     4                      1
15         00-0020337    2016     5                      1
16         00-0020337    2016     9                      4
17         00-0020337    2016    10                      1
18         00-0020337    2016    11                      1
19         00-0020337    2016    12                      1

In [44]:
games_per_player_season = (
    df.groupby(['receiver_player_id', 'season'])
      .size()
      .rename('games_in_season')
      .reset_index()
 )

player_seasons_over_3 = games_per_player_season[games_per_player_season['games_in_season'] > 3].copy()
player_seasons_over_5 = games_per_player_season[games_per_player_season['games_in_season'] > 5].copy()

total_players = games_per_player_season['receiver_player_id'].nunique()
total_player_seasons = len(games_per_player_season)

num_players_over_3 = player_seasons_over_3['receiver_player_id'].nunique()
num_player_seasons_over_3 = len(player_seasons_over_3)

num_players_over_5 = player_seasons_over_5['receiver_player_id'].nunique()
num_player_seasons_over_5 = len(player_seasons_over_5)

pct_players_over_3 = (num_players_over_3 / total_players) * 100
pct_player_seasons_over_3 = (num_player_seasons_over_3 / total_player_seasons) * 100

pct_players_over_5 = (num_players_over_5 / total_players) * 100
pct_player_seasons_over_5 = (num_player_seasons_over_5 / total_player_seasons) * 100

print(f'Ukupno igraca: {total_players}')
print(f'Igraca sa bar jednom sezonom >3 utakmice: {num_players_over_3} ({pct_players_over_3:.2f}%)')
print(f'Igraca sa bar jednom sezonom >5 utakmica: {num_players_over_5} ({pct_players_over_5:.2f}%)')
print('---')
print(f'Ukupno igrac-sezona kombinacija: {total_player_seasons}')
print(f'Kombinacija sa >3 utakmice: {num_player_seasons_over_3} ({pct_player_seasons_over_3:.2f}%)')
print(f'Kombinacija sa >5 utakmica: {num_player_seasons_over_5} ({pct_player_seasons_over_5:.2f}%)')

comparison = pd.DataFrame({
    'metric': [
        'Ukupno igraca',
        'Igraci sa bar jednom sezonom >3',
        'Igraci sa bar jednom sezonom >5',
        'Ukupno igrac-sezona kombinacija',
        'Igrac-sezona kombinacije >3',
        'Igrac-sezona kombinacije >5'
    ],
    'value': [
        total_players,
        num_players_over_3,
        num_players_over_5,
        total_player_seasons,
        num_player_seasons_over_3,
        num_player_seasons_over_5
    ]
})

comparison

Ukupno igraca: 1719
Igraca sa bar jednom sezonom >3 utakmice: 1200 (69.81%)
Igraca sa bar jednom sezonom >5 utakmica: 1077 (62.65%)
---
Ukupno igrac-sezona kombinacija: 5474
Kombinacija sa >3 utakmice: 3970 (72.52%)
Kombinacija sa >5 utakmica: 3432 (62.70%)

                            metric  value
0                    Ukupno igraca   1719
1  Igraci sa bar jednom sezonom >3   1200
2  Igraci sa bar jednom sezonom >5   1077
3  Ukupno igrac-sezona kombinacija   5474
4      Igrac-sezona kombinacije >3   3970
5      Igrac-sezona kombinacije >5   3432

In [5]:
# Inferred player team from matchup: offense is the opposite side of defteam.
df['player_team_inferred'] = np.where(
    (df['home_team'] == df['defteam']) & (df['away_team'] != df['defteam']),
    df['away_team'],
    np.where(
        (df['away_team'] == df['defteam']) & (df['home_team'] != df['defteam']),
        df['home_team'],
        np.nan
    )
)

prev_team = df.groupby('receiver_player_id')['player_team_inferred'].shift(1)
df['team_changed'] = (
    df['player_team_inferred'].notna()
    & prev_team.notna()
    & (df['player_team_inferred'] != prev_team)
).astype(int)

prev_season = df.groupby('receiver_player_id')['season'].shift(1)
df['is_new_season'] = (
    prev_season.notna()
    & (df['season'] != prev_season)
).astype(int)

unknown_team_rows = df['player_team_inferred'].isna().sum()
print(f'Rows with unresolved inferred team: {unknown_team_rows}')
print('team_changed distribution:')
print(df['team_changed'].value_counts(dropna=False).sort_index())
print('is_new_season distribution:')
print(df['is_new_season'].value_counts(dropna=False).sort_index())

df.loc[
    (df['team_changed'] == 1) | (df['is_new_season'] == 1),
    ['receiver_player_id', 'season', 'week', 'player_team_inferred', 'team_changed', 'is_new_season']
].head(20)

Rows with unresolved inferred team: 0
team_changed distribution:
team_changed
0    44982
1     1133
Name: count, dtype: int64
is_new_season distribution:
is_new_season
0    42360
1     3755
Name: count, dtype: int64

    receiver_player_id  season  week  player_team_inferred  team_changed  is_new_season
1           00-0019596    2017    21                  22.0             0              1
2           00-0019596    2018    10                  22.0             0              1
3           00-0019596    2022    10                  30.0             1              1
11          00-0020337    2016     1                   3.0             0              1
37          00-0021547    2016     1                  18.0             0              1
50          00-0021547    2017     1                  18.0             0              1
66          00-0021547    2018     1                  18.0             0              1
100         00-0022044    2016     1                  31.0             1              1
120         00-0022084    2016     1                  11.0             1              1
153         00-0022127    2016     1                   9.0             0              1
169         00-0022127    2017     1                   9.0             0              1
185         00-0022127    2019     1                   9.0             0              1
201         00-0022127    2020     1                  17.0             1              1
271         00-0022921    2016     1                   1.0             0              1
287         00-0022921    2017     1                   1.0             0              1
303         00-0022921    2018     1                   1.0             0              1
319         00-0022921    2019     1                   1.0             0              1
335         00-0022921    2020     1                   1.0             0              1
365         00-0022943    2017     1                   3.0             1              1
381         00-0022943    2018     1                  23.0             1              1

In [46]:
numeric_cols = df.select_dtypes(include=['number']).columns.tolist()
non_numeric_cols = df.select_dtypes(exclude=['number']).columns.tolist()

print(f"Ukupan broj kolona: {len(df.columns)}")
print(f"Numericke kolone ({len(numeric_cols)}):")
print(numeric_cols)
print()
print(f"Nenumericke kolone ({len(non_numeric_cols)}):")
print(non_numeric_cols)

Ukupan broj kolona: 104
Numericke kolone (100):
['defteam', 'targets', 'receptions', 'receiving_yards', 'air_yards', 'yac', 'tds', 'epa', 'wpa', 'avg_depth', 'catch_rate', 'posteam', 'team_pass_attempts', 'team_air_yards', 'team_epa', 'air_yard_share', 'target_share', 'yards_per_target', 'def_targets_dev', 'def_receptions_dev', 'def_yards_dev', 'def_tds_dev', 'def_epa_dev', 'red_zone_targets', 'end_zone_targets', 'third_down_targets', 'fourth_down_targets', 'high_leverage_targets', 'qb_completions', 'qb_attempts', 'qb_air_yards', 'qb_cpoe', 'qb_comp_pct', 'avg_score_diff', 'avg_quarter', 'adot', 'yac_per_reception', 'td_rate', 'explosive_plays', 'first_downs', 'trailing_pct', 'leading_pct', 'wp_var', 'target_share_std', 'surface', 'is_dome', 'is_rain', 'is_snow', 'is_clear', 'temp_f', 'humidity_pct', 'wind_mph', 'success_rate', 'big_play_rate', 'reception_std', 'second_and_long_targets', 'third_and_medium_targets', 'avg_start_yardline', 'avg_target_depth_vs_qb', 'yards_Q1', 'yards_Q2', 'yards_Q3', 'yards_Q4', 'receptions_Q1', 'receptions_Q2', 'receptions_Q3', 'receptions_Q4', 'targets_Q1', 'targets_Q2', 'targets_Q3', 'targets_Q4', 'lost_yards_due_to_penalty', 'yards_wp_<25', 'yards_wp_25_45', 'yards_wp_45_55', 'yards_wp_55_75', 'yards_wp_>75', 'yards_wp_NA', 'receptions_wp_<25', 'receptions_wp_25_45', 'receptions_wp_45_55', 'receptions_wp_55_75', 'receptions_wp_>75', 'receptions_wp_NA', 'targets_wp_<25', 'targets_wp_25_45', 'targets_wp_45_55', 'targets_wp_55_75', 'targets_wp_>75', 'targets_wp_NA', 'home_team', 'away_team', 'pregame_spread', 'pregame_total', 'season', 'week', 'weeks_since_last_game', 'player_team_inferred', 'team_changed', 'is_new_season']

Nenumericke kolone (4):
['game_id', 'receiver_player_id', 'receiver_player_name', 'passer_player_id']

In [6]:
# STEP 5/6/8/9 — Leakage-safe feature engineering

work_df = df.copy().sort_values(['receiver_player_id', 'season', 'week']).reset_index(drop=True)

# Align WP column names with the requested naming convention.
wp_rename_map = {
    'yards_wp_<25': 'yards_wp_less_than_25',
    'yards_wp_>75': 'yards_wp_greater_than_75',
    'receptions_wp_<25': 'receptions_wp_less_than_25',
    'receptions_wp_>75': 'receptions_wp_greater_than_75',
    'targets_wp_<25': 'targets_wp_less_than_25',
    'targets_wp_>75': 'targets_wp_greater_than_75',
}
work_df = work_df.rename(columns={k: v for k, v in wp_rename_map.items() if k in work_df.columns})

# STEP 8 — previous-season career features.
season_career = (
    work_df.groupby(['receiver_player_id', 'season'], as_index=False)
    .agg(
        avg_yards=('receiving_yards', 'mean'),
        avg_target_share=('target_share', 'mean'),
        avg_epa=('epa', 'mean'),
        avg_air_yard_share=('air_yard_share', 'mean'),
        avg_catch_rate=('catch_rate', 'mean'),
        games_played=('game_id', 'count')
    )
    .sort_values(['receiver_player_id', 'season'])
)

for c in ['avg_yards', 'avg_target_share', 'avg_epa', 'avg_air_yard_share', 'avg_catch_rate', 'games_played']:
    season_career[f'{c}_last_season'] = season_career.groupby('receiver_player_id')[c].shift(1)

season_career = season_career[[
    'receiver_player_id', 'season',
    'avg_yards_last_season',
    'avg_target_share_last_season',
    'avg_epa_last_season',
    'avg_air_yard_share_last_season',
    'avg_catch_rate_last_season',
    'games_played_last_season'
]].rename(columns={
    'avg_yards_last_season': 'career_avg_yards_last_season',
    'avg_target_share_last_season': 'career_avg_target_share_last_season',
    'avg_epa_last_season': 'career_avg_epa_last_season',
    'avg_air_yard_share_last_season': 'career_avg_air_yard_share_last_season',
    'avg_catch_rate_last_season': 'career_avg_catch_rate_last_season',
    'games_played_last_season': 'career_games_last_season',
})

work_df = work_df.merge(season_career, on=['receiver_player_id', 'season'], how='left')
career_cols = [
    'career_avg_yards_last_season',
    'career_avg_target_share_last_season',
    'career_avg_epa_last_season',
    'career_avg_air_yard_share_last_season',
    'career_avg_catch_rate_last_season',
    'career_games_last_season',
]
work_df[career_cols] = work_df[career_cols].fillna(0)

# STEP 9 — lag1, roll3, roll5 from previous games only (shift(1) before rolling).
rolling_source_cols = [
    'targets', 'receptions', 'air_yards', 'yac', 'tds', 'epa', 'wpa', 'catch_rate',
    'avg_depth', 'adot', 'yac_per_reception', 'td_rate', 'explosive_plays', 'first_downs',
    'yards_per_target', 'team_pass_attempts', 'team_air_yards', 'team_epa', 'air_yard_share',
    'target_share', 'qb_completions', 'qb_attempts', 'qb_air_yards', 'qb_cpoe', 'qb_comp_pct',
    'avg_score_diff', 'trailing_pct', 'leading_pct', 'avg_quarter', 'success_rate',
    'big_play_rate', 'avg_start_yardline', 'red_zone_targets', 'end_zone_targets',
    'third_down_targets', 'fourth_down_targets', 'high_leverage_targets',
    'second_and_long_targets', 'third_and_medium_targets', 'wp_var', 'target_share_std',
    'reception_std', 'def_targets_dev', 'def_receptions_dev', 'def_yards_dev', 'def_tds_dev',
    'def_epa_dev', 'yards_Q1', 'yards_Q2', 'yards_Q3', 'yards_Q4', 'receptions_Q1',
    'receptions_Q2', 'receptions_Q3', 'receptions_Q4', 'targets_Q1', 'targets_Q2',
    'targets_Q3', 'targets_Q4', 'lost_yards_due_to_penalty', 'yards_wp_less_than_25',
    'yards_wp_25_45', 'yards_wp_45_55', 'yards_wp_55_75', 'yards_wp_greater_than_75',
    'receptions_wp_less_than_25', 'receptions_wp_25_45', 'receptions_wp_45_55',
    'receptions_wp_55_75', 'receptions_wp_greater_than_75', 'targets_wp_less_than_25',
    'targets_wp_25_45', 'targets_wp_45_55', 'targets_wp_55_75', 'targets_wp_greater_than_75',
    'weeks_since_last_game'
]
available_roll_cols = [c for c in rolling_source_cols if c in work_df.columns]

grp = work_df.groupby(['receiver_player_id', 'season'], sort=False)
derived_roll_cols = []
for col in available_roll_cols:
    work_df[f'{col}_lag1'] = grp[col].transform(lambda s: s.shift(1))
    work_df[f'{col}_roll3'] = grp[col].transform(lambda s: s.shift(1).rolling(window=3, min_periods=1).mean())
    work_df[f'{col}_roll5'] = grp[col].transform(lambda s: s.shift(1).rolling(window=5, min_periods=1).mean())
    derived_roll_cols.extend([f'{col}_lag1', f'{col}_roll3', f'{col}_roll5'])

# Drop raw in-game columns used for rolling to prevent leakage.
work_df = work_df.drop(columns=available_roll_cols)

# STEP 6 direct pre-game features only.
pregame_features = [
    'pregame_spread', 'pregame_total', 'surface', 'is_dome', 'temp_f', 'humidity_pct',
    'wind_mph', 'is_rain', 'is_snow', 'is_clear', 'season', 'week', 'team_changed', 'is_new_season'
]

missing_pregame = [c for c in pregame_features if c not in work_df.columns]
if missing_pregame:
    raise ValueError(f'Missing required pre-game features: {missing_pregame}')

feature_cols = pregame_features + career_cols + derived_roll_cols

# Keep target separately for training, while features remain leakage-safe.
target_col = 'receiving_yards'
model_df = work_df[['receiver_player_id', 'receiver_player_name', 'game_id', target_col] + feature_cols].copy()

print(f'Final model_df shape: {model_df.shape}')
print(f'Number of leakage-safe features: {len(feature_cols)}')
print('Preview feature columns:')
print(feature_cols[:25])
print('...')
print(feature_cols[-10:])
print('\nCareer features head:')
print(model_df[career_cols].head())

Final model_df shape: (46115, 252)
Number of leakage-safe features: 248
Preview feature columns:
['pregame_spread', 'pregame_total', 'surface', 'is_dome', 'temp_f', 'humidity_pct', 'wind_mph', 'is_rain', 'is_snow', 'is_clear', 'season', 'week', 'team_changed', 'is_new_season', 'career_avg_yards_last_season', 'career_avg_target_share_last_season', 'career_avg_epa_last_season', 'career_avg_air_yard_share_last_season', 'career_avg_catch_rate_last_season', 'career_games_last_season', 'targets_lag1', 'targets_roll3', 'targets_roll5', 'receptions_lag1', 'receptions_roll3']
...
['targets_wp_45_55_roll5', 'targets_wp_55_75_lag1', 'targets_wp_55_75_roll3', 'targets_wp_55_75_roll5', 'targets_wp_greater_than_75_lag1', 'targets_wp_greater_than_75_roll3', 'targets_wp_greater_than_75_roll5', 'weeks_since_last_game_lag1', 'weeks_since_last_game_roll3', 'weeks_since_last_game_roll5']

Career features head:
   career_avg_yards_last_season  career_avg_target_share_last_season  career_avg_epa_last_season  \
0                           0.0                             0.000000                    0.000000
1                          36.0                             0.017857                    3.129031
2                           0.0                             0.021277                   -1.000783
3                           6.0                             0.025000                   -0.220586
4                           0.0                             0.000000                    0.000000

   career_avg_air_yard_share_last_season  career_avg_catch_rate_last_season  career_games_last_season
0                               0.000000                                0.0                       0.0
1                               0.012259                                1.0                       1.0
2                               0.012522                                0.0                       1.0
3                               0.000000                                1.0                       1.0
4                               0.000000                                0.0                       0.0

In [51]:
# Quick validation checks
print('surface unique values in model_df:', sorted(model_df['surface'].dropna().unique().tolist()))
print(model_df['surface'].value_counts(dropna=False).sort_index())

raw_cols_still_present = [c for c in rolling_source_cols if c in feature_cols]
print('\nRaw rolling-source columns still in feature set (should be empty):')
print(raw_cols_still_present)

print('\nAny duplicated feature names:', len(feature_cols) != len(set(feature_cols)))

surface unique values in model_df: [0, 1, 2, 3, 4, 5, 6]
surface
0     2354
1     1175
2    24373
3     2532
4    11286
5     2589
6     1806
Name: count, dtype: int64

Raw rolling-source columns still in feature set (should be empty):
[]

Any duplicated feature names: False

In [55]:
model_df.iloc[10:21]

,receiver_player_id,receiver_player_name,game_id,receiving_yards,pregame_spread,pregame_total,surface,is_dome,temp_f,humidity_pct,wind_mph,is_rain,is_snow,is_clear,season,week,team_changed,is_new_season,career_avg_yards_last_season,career_avg_target_share_last_season,career_avg_epa_last_season,career_avg_air_yard_share_last_season,career_avg_catch_rate_last_season,career_games_last_season,targets_lag1,...,receptions_wp_45_55_roll5,receptions_wp_55_75_lag1,receptions_wp_55_75_roll3,receptions_wp_55_75_roll5,receptions_wp_greater_than_75_lag1,receptions_wp_greater_than_75_roll3,receptions_wp_greater_than_75_roll5,targets_wp_less_than_25_lag1,targets_wp_less_than_25_roll3,targets_wp_less_than_25_roll5,targets_wp_25_45_lag1,targets_wp_25_45_roll3,targets_wp_25_45_roll5,targets_wp_45_55_lag1,targets_wp_45_55_roll3,targets_wp_45_55_roll5,targets_wp_55_75_lag1,targets_wp_55_75_roll3,targets_wp_55_75_roll5,targets_wp_greater_than_75_lag1,targets_wp_greater_than_75_roll3,targets_wp_greater_than_75_roll5,weeks_since_last_game_lag1,weeks_since_last_game_roll3,weeks_since_last_game_roll5
10,00-0020337,S.Smith,2015_08_SD_BAL,82.0,4.5,50.0,3,0,63.0,72.0,10.0,0,0,1,2015,8,0,0,0.000000,0.00000,0.000000,0.00000,0.000000,0.0,9.0,...,1.400000,0.0,0.333333,1.0,0.0,0.000000,0.00,9.0,4.666667,4.60,0.0,1.666667,3.200000,0.0,1.333333,2.200000,0.0,0.666667,1.4,0.0,0.333333,0.40,1.0,1.333333,1.2
11,00-0020337,S.Smith,2016_01_BUF_BAL,19.0,3.0,44.5,2,0,84.0,44.0,8.0,0,0,1,2016,1,0,1,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,00-0020337,S.Smith,2016_02_BAL_CLE,64.0,-4.0,42.0,2,0,74.0,70.0,7.0,0,0,1,2016,2,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,8.0,...,0.000000,4.0,4.000000,4.0,1.0,1.000000,1.00,0.0,0.000000,0.00,0.0,0.000000,0.000000,0.0,0.000000,0.000000,7.0,7.000000,7.0,1.0,1.000000,1.00,1.0,1.000000,1.0
13,00-0020337,S.Smith,2016_03_BAL_JAX,87.0,-1.0,45.0,2,0,88.0,0.0,8.0,0,0,1,2016,3,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,6.0,...,0.000000,0.0,2.000000,2.0,0.0,0.500000,0.50,0.0,0.000000,0.00,6.0,3.000000,3.000000,0.0,0.000000,0.000000,0.0,3.500000,3.5,0.0,0.500000,0.50,1.0,1.000000,1.0
14,00-0020337,S.Smith,2016_04_OAK_BAL,111.0,3.5,45.0,2,0,65.0,84.0,2.0,0,0,1,2016,4,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,11.0,...,0.666667,2.0,2.000000,2.0,2.0,1.000000,1.00,0.0,0.000000,0.00,2.0,2.666667,2.666667,2.0,0.666667,0.666667,5.0,4.000000,4.0,2.0,1.000000,1.00,1.0,1.000000,1.0
15,00-0020337,S.Smith,2016_05_WAS_BAL,29.0,4.0,44.5,2,0,62.0,53.0,16.0,0,0,1,2016,5,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,12.0,...,1.500000,0.0,0.666667,1.5,0.0,0.666667,0.75,3.0,1.000000,0.75,1.0,3.000000,2.250000,8.0,3.333333,2.500000,0.0,1.666667,3.0,0.0,0.666667,0.75,1.0,1.000000,1.0
16,00-0020337,S.Smith,2016_09_PIT_BAL,47.0,-3.5,46.0,2,0,65.0,28.0,15.0,0,0,1,2016,9,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,3.0,...,1.200000,1.0,1.000000,1.4,2.0,1.333333,1.00,0.0,1.000000,0.60,0.0,1.000000,1.800000,0.0,3.333333,2.000000,1.0,2.000000,2.6,2.0,1.333333,1.00,1.0,1.000000,1.0
17,00-0020337,S.Smith,2016_10_CLE_BAL,60.0,7.5,44.0,2,0,54.0,48.0,3.0,0,0,1,2016,10,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,8.0,...,1.200000,3.0,1.333333,1.2,0.0,0.666667,0.80,0.0,1.000000,0.60,1.0,0.666667,2.000000,1.0,3.000000,2.200000,4.0,1.666667,2.0,2.0,1.333333,1.20,4.0,2.000000,1.6
18,00-0020337,S.Smith,2016_11_BAL_DAL,99.0,7.0,44.5,5,0,0.0,0.0,0.0,0,0,1,2016,11,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,7.0,...,1.400000,3.0,2.333333,1.8,1.0,1.000000,1.00,0.0,0.000000,0.60,0.0,0.333333,0.800000,2.0,1.000000,2.600000,3.0,2.666667,2.6,2.0,2.000000,1.60,1.0,2.000000,1.6
19,00-0020337,S.Smith,2016_12_CIN_BAL,20.0,3.5,42.0,2,0,50.0,37.0,12.0,0,0,1,2016,12,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,9.0,...,1.200000,0.0,2.000000,1.4,0.0,0.333333,0.60,5.0,1.666667,1.60,3.0,1.333333,1.000000,1.0,1.333333,2.400000,0.0,2.333333,1.6,0.0,1.333333,1.20,1.0,2.000000,1.6
20,00-0020337,S.Smith,2016_13_MIA_BAL,48.0,3.5,41.5,2,0,47.0,60.0,3.0,0,0,1,2016,13,0,0,95.714286,0.26336,3.202514,0.30797,0.602384,7.0,4.0,...,0.400000,1.0,1.333333,1.6,3.0,1.333333,1.20,0.0,1.666667,1.00,0.0,1.000000,0.800000,0.0,1.000000,0.800000,1.0,1.333333,1.8,3.0,1.666667,1.80,1.0,1.000000,1.6

In [57]:
# Validation check for one player: all seasons and all games
player_summary = (
    model_df.groupby(['receiver_player_id', 'receiver_player_name'])
    .size()
    .reset_index(name='num_games')
    .sort_values('num_games', ascending=False)
)

# Pick one player with many games so the check is meaningful.
chosen_player_id = player_summary.iloc[0]['receiver_player_id']
chosen_player_name = player_summary.iloc[0]['receiver_player_name']

player_rows = (
    model_df[model_df['receiver_player_id'] == chosen_player_id]
    .sort_values(['season', 'week'])
    .reset_index(drop=True)
)

player_seasons = player_rows['season'].drop_duplicates().tolist()
player_games = player_rows['game_id'].tolist()

print(f'Player: {chosen_player_name} ({chosen_player_id})')
print(f'Ukupno utakmica: {len(player_games)}')
print(f'Sve sezone ({len(player_seasons)}): {player_seasons}')
print('\nSve utakmice (game_id):')
print(player_games)

# Show all columns and more rows for inspection.
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 220)
player_rows.head(50)

Player: T.Kelce (00-0030506)
Ukupno utakmica: 191
Sve sezone (11): [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

Sve utakmice (game_id):
['2015_01_KC_HOU', '2015_02_DEN_KC', '2015_03_KC_GB', '2015_04_KC_CIN', '2015_05_CHI_KC', '2015_06_KC_MIN', '2015_07_PIT_KC', '2015_08_DET_KC', '2015_10_KC_DEN', '2015_11_KC_SD', '2015_12_BUF_KC', '2015_13_KC_OAK', '2015_14_SD_KC', '2015_15_KC_BAL', '2015_16_CLE_KC', '2015_17_OAK_KC', '2015_18_KC_HOU', '2015_19_KC_NE', '2016_01_SD_KC', '2016_02_KC_HOU', '2016_03_NYJ_KC', '2016_04_KC_PIT', '2016_06_KC_OAK', '2016_07_NO_KC', '2016_08_KC_IND', '2016_09_JAX_KC', '2016_10_KC_CAR', '2016_11_TB_KC', '2016_12_KC_DEN', '2016_13_KC_ATL', '2016_14_OAK_KC', '2016_15_TEN_KC', '2016_16_DEN_KC', '2016_17_KC_SD', '2016_19_PIT_KC', '2017_01_KC_NE', '2017_02_PHI_KC', '2017_03_KC_LAC', '2017_04_WAS_KC', '2017_05_KC_HOU', '2017_06_PIT_KC', '2017_07_KC_OAK', '2017_08_DEN_KC', '2017_09_KC_DAL', '2017_11_KC_NYG', '2017_12_BUF_KC', '2017_13_KC_NYJ', '2017_14_OAK_KC', '2017_15_LAC_KC', '2017_16_MIA_KC', '2017_18_TEN_KC', '2018_01_KC_LAC', '2018_02_KC_PIT', '2018_03_SF_KC', '2018_04_KC_DEN', '2018_05_JAX_KC', '2018_06_KC_NE', '2018_07_CIN_KC', '2018_08_DEN_KC', '2018_09_KC_CLE', '2018_10_ARI_KC', '2018_11_KC_LA', '2018_13_KC_OAK', '2018_14_BAL_KC', '2018_15_LAC_KC', '2018_16_KC_SEA', '2018_17_OAK_KC', '2018_19_IND_KC', '2018_20_NE_KC', '2019_01_KC_JAX', '2019_02_KC_OAK', '2019_03_BAL_KC', '2019_04_KC_DET', '2019_05_IND_KC', '2019_06_HOU_KC', '2019_07_KC_DEN', '2019_08_GB_KC', '2019_09_MIN_KC', '2019_10_KC_TEN', '2019_11_KC_LAC', '2019_13_OAK_KC', '2019_14_KC_NE', '2019_15_DEN_KC', '2019_16_KC_CHI', '2019_17_LAC_KC', '2019_19_HOU_KC', '2019_20_TEN_KC', '2019_21_SF_KC', '2020_01_HOU_KC', '2020_02_KC_LAC', '2020_03_KC_BAL', '2020_04_NE_KC', '2020_05_LV_KC', '2020_06_KC_BUF', '2020_07_KC_DEN', '2020_08_NYJ_KC', '2020_09_CAR_KC', '2020_11_KC_LV', '2020_12_KC_TB', '2020_13_DEN_KC', '2020_14_KC_MIA', '2020_15_KC_NO', '2020_16_ATL_KC', '2020_19_CLE_KC', '2020_20_BUF_KC', '2020_21_KC_TB', '2021_01_CLE_KC', '2021_02_KC_BAL', '2021_03_LAC_KC', '2021_04_KC_PHI', '2021_05_BUF_KC', '2021_06_KC_WAS', '2021_07_KC_TEN', '2021_08_NYG_KC', '2021_09_GB_KC', '2021_10_KC_LV', '2021_11_DAL_KC', '2021_13_DEN_KC', '2021_14_LV_KC', '2021_15_KC_LAC', '2021_17_KC_CIN', '2021_18_KC_DEN', '2021_19_PIT_KC', '2021_20_BUF_KC', '2021_21_CIN_KC', '2022_01_KC_ARI', '2022_02_LAC_KC', '2022_03_KC_IND', '2022_04_KC_TB', '2022_05_LV_KC', '2022_06_BUF_KC', '2022_07_KC_SF', '2022_09_TEN_KC', '2022_10_JAX_KC', '2022_11_KC_LAC', '2022_12_LA_KC', '2022_13_KC_CIN', '2022_14_KC_DEN', '2022_15_KC_HOU', '2022_16_SEA_KC', '2022_17_DEN_KC', '2022_18_KC_LV', '2022_20_JAX_KC', '2022_21_CIN_KC', '2022_22_KC_PHI', '2023_02_KC_JAX', '2023_03_CHI_KC', '2023_04_KC_NYJ', '2023_05_KC_MIN', '2023_06_DEN_KC', '2023_07_LAC_KC', '2023_08_KC_DEN', '2023_09_MIA_KC', '2023_11_PHI_KC', '2023_12_KC_LV', '2023_13_KC_GB', '2023_14_BUF_KC', '2023_15_KC_NE', '2023_16_LV_KC', '2023_17_CIN_KC', '2023_19_MIA_KC', '2023_20_KC_BUF', '2023_21_KC_BAL', '2023_22_SF_KC', '2024_01_BAL_KC', '2024_02_CIN_KC', '2024_03_KC_ATL', '2024_04_KC_LAC', '2024_05_NO_KC', '2024_07_KC_SF', '2024_08_KC_LV', '2024_09_TB_KC', '2024_10_DEN_KC', '2024_11_KC_BUF', '2024_12_KC_CAR', '2024_13_LV_KC', '2024_14_LAC_KC', '2024_15_KC_CLE', '2024_16_HOU_KC', '2024_17_KC_PIT', '2024_20_HOU_KC', '2024_21_BUF_KC', '2024_22_KC_PHI', '2025_01_KC_LAC', '2025_02_PHI_KC', '2025_03_KC_NYG', '2025_04_BAL_KC', '2025_05_KC_JAX', '2025_06_DET_KC', '2025_07_LV_KC', '2025_08_WAS_KC']

,receiver_player_id,receiver_player_name,game_id,receiving_yards,pregame_spread,pregame_total,surface,is_dome,temp_f,humidity_pct,wind_mph,is_rain,is_snow,is_clear,season,week,team_changed,is_new_season,career_avg_yards_last_season,career_avg_target_share_last_season,career_avg_epa_last_season,career_avg_air_yard_share_last_season,career_avg_catch_rate_last_season,career_games_last_season,targets_lag1,targets_roll3,targets_roll5,receptions_lag1,receptions_roll3,receptions_roll5,air_yards_lag1,air_yards_roll3,air_yards_roll5,yac_lag1,yac_roll3,yac_roll5,tds_lag1,tds_roll3,tds_roll5,epa_lag1,epa_roll3,epa_roll5,wpa_lag1,wpa_roll3,wpa_roll5,catch_rate_lag1,catch_rate_roll3,catch_rate_roll5,avg_depth_lag1,avg_depth_roll3,avg_depth_roll5,adot_lag1,adot_roll3,adot_roll5,yac_per_reception_lag1,yac_per_reception_roll3,yac_per_reception_roll5,td_rate_lag1,td_rate_roll3,td_rate_roll5,explosive_plays_lag1,explosive_plays_roll3,explosive_plays_roll5,first_downs_lag1,first_downs_roll3,first_downs_roll5,yards_per_target_lag1,yards_per_target_roll3,yards_per_target_roll5,team_pass_attempts_lag1,team_pass_attempts_roll3,team_pass_attempts_roll5,team_air_yards_lag1,team_air_yards_roll3,team_air_yards_roll5,team_epa_lag1,team_epa_roll3,team_epa_roll5,air_yard_share_lag1,air_yard_share_roll3,air_yard_share_roll5,target_share_lag1,target_share_roll3,target_share_roll5,qb_completions_lag1,qb_completions_roll3,qb_completions_roll5,qb_attempts_lag1,qb_attempts_roll3,qb_attempts_roll5,qb_air_yards_lag1,qb_air_yards_roll3,qb_air_yards_roll5,qb_cpoe_lag1,qb_cpoe_roll3,qb_cpoe_roll5,qb_comp_pct_lag1,qb_comp_pct_roll3,qb_comp_pct_roll5,avg_score_diff_lag1,avg_score_diff_roll3,avg_score_diff_roll5,trailing_pct_lag1,trailing_pct_roll3,trailing_pct_roll5,leading_pct_lag1,leading_pct_roll3,leading_pct_roll5,avg_quarter_lag1,avg_quarter_roll3,avg_quarter_roll5,success_rate_lag1,success_rate_roll3,success_rate_roll5,big_play_rate_lag1,big_play_rate_roll3,big_play_rate_roll5,avg_start_yardline_lag1,avg_start_yardline_roll3,avg_start_yardline_roll5,red_zone_targets_lag1,red_zone_targets_roll3,red_zone_targets_roll5,end_zone_targets_lag1,end_zone_targets_roll3,end_zone_targets_roll5,third_down_targets_lag1,third_down_targets_roll3,third_down_targets_roll5,fourth_down_targets_lag1,fourth_down_targets_roll3,fourth_down_targets_roll5,high_leverage_targets_lag1,high_leverage_targets_roll3,high_leverage_targets_roll5,second_and_long_targets_lag1,second_and_long_targets_roll3,second_and_long_targets_roll5,third_and_medium_targets_lag1,third_and_medium_targets_roll3,third_and_medium_targets_roll5,wp_var_lag1,wp_var_roll3,wp_var_roll5,target_share_std_lag1,target_share_std_roll3,target_share_std_roll5,reception_std_lag1,reception_std_roll3,reception_std_roll5,def_targets_dev_lag1,def_targets_dev_roll3,def_targets_dev_roll5,def_receptions_dev_lag1,def_receptions_dev_roll3,def_receptions_dev_roll5,def_yards_dev_lag1,def_yards_dev_roll3,def_yards_dev_roll5,def_tds_dev_lag1,def_tds_dev_roll3,def_tds_dev_roll5,def_epa_dev_lag1,def_epa_dev_roll3,def_epa_dev_roll5,yards_Q1_lag1,yards_Q1_roll3,yards_Q1_roll5,yards_Q2_lag1,yards_Q2_roll3,yards_Q2_roll5,yards_Q3_lag1,yards_Q3_roll3,yards_Q3_roll5,yards_Q4_lag1,yards_Q4_roll3,yards_Q4_roll5,receptions_Q1_lag1,receptions_Q1_roll3,receptions_Q1_roll5,receptions_Q2_lag1,receptions_Q2_roll3,receptions_Q2_roll5,receptions_Q3_lag1,receptions_Q3_roll3,receptions_Q3_roll5,receptions_Q4_lag1,receptions_Q4_roll3,receptions_Q4_roll5,targets_Q1_lag1,targets_Q1_roll3,targets_Q1_roll5,targets_Q2_lag1,targets_Q2_roll3,targets_Q2_roll5,targets_Q3_lag1,targets_Q3_roll3,targets_Q3_roll5,targets_Q4_lag1,targets_Q4_roll3,targets_Q4_roll5,lost_yards_due_to_penalty_lag1,lost_yards_due_to_penalty_roll3,lost_yards_due_to_penalty_roll5,yards_wp_less_than_25_lag1,yards_wp_less_than_25_roll3,yards_wp_less_than_25_roll5,yards_wp_25_45_lag1,yards_wp_25_45_roll3,yards_wp_25_45_roll5,yards_wp_45_55_lag1,yards_wp_45_55_roll3,yards_wp_45_55_roll5,yards_wp_55_75_lag1,yards_wp_55_75_roll3,yards_wp_55_75_roll5,yards_wp_greater_than_75_lag1,yards_wp_greater_than_75_roll3,yards_wp_greater_than_75_roll5,receptions_wp_less_than_25_lag1,receptions_wp_less_than_25_roll3,receptions_wp_less_than_25_roll5,receptions_wp_25_45_lag1,receptions_wp_25_45_roll3,receptions_wp_25_45_roll5,receptions_wp_45_55_lag1,receptions_wp_45_55_roll3,receptions_wp_45_55_roll5,receptions_wp_55_75_lag1,receptions_wp_55_75_roll3,receptions_wp_55_75_roll5,receptions_wp_greater_than_75_lag1,receptions_wp_greater_than_75_roll3,receptions_wp_greater_than_75_roll5,targets_wp_less_than_25_lag1,targets_wp_less_than_25_roll3,targets_wp_less_than_25_roll5,targets_wp_25_45_lag1,targets_wp_25_45_roll3,targets_wp_25_45_roll5,targets_wp_45_55_lag1,targets_wp_45_55_roll3,targets_wp_45_55_roll5,targets_wp_55_75_lag1,targets_wp_55_75_roll3,targets_wp_55_75_roll5,targets_wp_greater_than_75_lag1,targets_wp_greater_than_75_roll3,targets_wp_greater_than_75_roll5,weeks_since_last_game_lag1,weeks_since_last_game_roll3,weeks_since_last_game_roll5
0,00-0030506,T.Kelce,2015_01_KC_HOU,106.0,-1.0,41.0,2,0,80.0,38.0,10.0,0,0,1,2015,1,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00-0030506,T.Kelce,2015_02_DEN_KC,58.0,3.0,42.0,2,0,87.0,59.0,13.0,0,0,1,2015,2,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,6.0,6.000000,6.000000,6.0,6.000000,6.000000,58.0,58.000000,58.000000,48.0,48.000000,48.000000,2.0,2.000000,2.000000,11.516493,11.516493,11.516493,0.149933,0.149933,0.149933,1.000000,1.000000,1.000000,9.666667,9.666667,9.666667,9.666667,9.666667,9.666667,8.000000,8.000000,8.000000,0.333333,0.333333,0.333333,1.0,1.000000,1.000000,5.0,5.000000,5.000000,17.666667,17.666667,17.666667,47.0,47.000000,47.000000,475.0,475.000000,475.000000,6.042255,6.042255,6.042255,0.122105,0.122105,0.122105,0.127660,0.127660,0.127660,22.0,22.000000,22.000000,31.0,31.000000,31.000000,5.967742,5.967742,5.967742,1.300107,1.300107,1.300107,0.709677,0.709677,0.709677,17.000000,17.000000,17.000000,0.0,0.0,0.0,0.833333,0.833333,0.833333,2.500000,2.500000,2.500000,1.000000,1.000000,1.000000,0.166667,0.166667,0.166667,53.833333,53.833333,53.833333,1.0,1.000000,1.000000,0.0,0.0,0.0,1.0,1.000000,1.000000,0.0,0.000000,0.000000,3.0,3.000000,3.000000,2.0,2.000000,2.000000,1.0,1.000000,1.000000,0.028094,0.028094,0.028094,0.081655,0.081655,0.081655,12.436505,12.436505,12.436505,0.943029,0.943029,0.943029,0.897794,0.897794,0.897794,0.878646,0.878646,0.878646,0.899382,0.899382,0.899382,0.312281,0.312281,0.312281,52.0,52.000000,52.000000,18.0,18.000000,18.000000,9.0,9.000000,9.000000,27.0,27.000000,27.000000,2.0,2.000000,2.000000,1.0,1.000000,1.000000,1.0,1.000000,1.000000,2.0,2.000000,2.000000,2.0,2.000000,2.000000,1.0,1.000000,1.000000,1.0,1.000000,1.000000,2.0,2.000000,2.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,10.0,10.000000,10.000000,96.0,96.000000,96.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.0,1.000000,1.000000,5.0,5.000000,5.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.0,1.000000,1.000000,5.0,5.000000,5.000000,1.0,1.000000,1.0
2,00-0030506,T.Kelce,2015_03_KC_GB,80.0,4.5,47.0,2,0,67.0,93.0,5.0,0,0,1,2015,3,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,5.0,5.500000,5.500000,4.0,5.000000,5.000000,26.0,42.000000,42.000000,37.0,42.500000,42.500000,0.0,1.000000,1.000000,4.578143,8.047318,8.047318,0.175772,0.162852,0.162852,0.800000,0.900000,0.900000,5.200000,7.433333,7.433333,5.200000,7.433333,7.433333,9.250000,8.625000,8.625000,0.000000,0.166667,0.166667,1.0,1.000000,1.000000,3.0,4.000000,4.000000,11.600000,14.633333,14.633333,45.0,46.000000,46.000000,452.0,463.500000,463.500000,2.798952,4.420604,4.420604,0.057522,0.089814,0.089814,0.111111,0.119385,0.119385,16.0,19.000000,19.000000,25.0,28.000000,28.000000,4.520000,5.243871,5.243871,-6.368473,-2.534183,-2.534183,0.640000,0.674839,0.674839,12.400000,14.700000,14.700000,0.0,0.0,0.0,0.800000,0.816667,0.816667,3.000000,2.750000,2.750000,0.800000,0.900000,0.900000,0.200000,0.183333,0.183333,56.600000,55.216667,55.216667,1.0,1.000000,1.000000,0.0,0.0,0.0,0.0,0.500000,0.500000,0.0,0.000000,0.000000,0.0,1.500000,1.500000,2.0,2.000000,2.000000,0.0,0.500000,0.500000,0.002068,0.015081,0.015081,0.081655,0.081655,0.081655,10.503968,11.470236,11.470236,1.044305,0.993667,0.993667,0.967226,0.932510,0.932510,0.904681,0.891663,0.891663,0.643768,0.771575,0.771575,-0.076333,0.117974,0.117974,15.0,33.500000,33.500000,0.0,9.000000,9.000000,5.0,7.000000,7.000000,38.0,32.500000,32.500000,1.0,1.500000,1.500000,0.0,0.500000,0.500000,1.0,1.000000,1.000000,2.0,2.000000,2.000000,1.0,1.500000,1.500000,0.0,0.500000,0.500000,2.0,1.500000,1.500000,2.0,2.000000,2.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,58.0,34.000000,34.000000,0.0,48.000000,48.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,4.0,2.500000,2.500000,0.0,2.500000,2.500000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,5.0,3.000000,3.000000,0.0,2.500000,2.500000,1.0,1.000000,1.0
3,00-0030506,T.Kelce,2015_04_KC_CIN,49.0,3.5,45.0,4,0,68.0,64.0,5.0,0,0,1,2015,4,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,11.0,7.333333,7.333333,6.0,5.333333,5.333333,47.0,43.666667,43.666667,60.0,48.333333,48.333333,0.0,0.666667,0.666667,3.231377,6.442004,6.442004,-0.004262,0.107148,0.107148,0.545455,0.781818,0.781818,4.700000,6.522222,6.522222,4.272727,6.379798,6.379798,10.000000,9.083333,9.083333,0.000000,0.111111,0.111111,2.0,1.333333,1.333333,4.0,4.000000,4.000000,7.272727,12.179798,12.179798,35.0,42.333333,42.333333,280.0,402.333333,402.333333,17.240569,8.693925,8.693925,0.167857,0.115828,0.115828,0.314286,0.184352,0.184352,24.0,20.666667,20.666667,42.0,32.666667,32.666667,6.300000,5.595914,5.595914,-9.531790,-4.866719,-4.866719,0.571429,0.640369,0.640369,10.272727,13.224242,13.224242,0.0,0.0,0.0,0.818182,0.817172,0.817172,3.181818,2.893939,2.893939,0.545455,0.781818,0.781818,0.181818,0.182828,0.182828,55.090909,55.174747,55.174747,3.0,1.666667,1.666667,0.0,0.0,0.0,1.0,0.666667,0.666667,0.0,0.000000,0.000000,11.0,4.666667,4.666667,1.0,1.666667,1.666667,0.0,0.333333,0.333333,0.004546,0.011569,0.011569,0.081655,0.081655,0.081655,14.445299,12.461924,12.461924,0.986288,0.991207,0.991207,0.927023,0.930681,0.930681,0.981979,0.921769,0.921769,0.815440,0.786197,0.786197,0.584345,0.273431,0.273431,0.0,22.333333,22.333333,38.0,18.666667,18.666667,28.0,14.000000,14.000000,14.0,26.333333,26.333333,0.0,1.000000,1.000000,1.0,0.666667,0.666667,4.0,2.000000,2.000000,1.0,1.666667,1.666667,0.0,1.000000,1.000000,2.0,1.000000,1.000000,5.0,2.666667,2.666667,4.0,2.666667,2.666667,0.0,0.0,0.0,80.0,26.666667,26.666667,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,22.666667,22.666667,0.0,32.000000,32.000000,6.0,2.000000,2.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,1.666667,1.666667,0.0,1.666667,1.666667,11.0,3.666667,3.666667,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,2.000000,2.000000,0.0,1.666667,1.666667,1.0,1.000000,1.0
4,00-0030506,T.Kelce,2015_05_CHI_KC,35.0,10.0,44.0,2,0,72.0,51.0,0.0,0,0,1,2015,5,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,7.0,7.666667,7.250000,5.0,5.000000,5.250000,17.0,30.000000,37.000000,43.0,46.666667,47.000000,0.0,0.000000,0.500000,-2.767849,1.680557,4.139541,-0.039842,0.043889,0.070400,0.714286,0.686580,0.764935,2.428571,4.109524,5.498810,2.428571,3.967100,5.391991,8.600000,9.283333,8.962500,0.000000,0.000000,0.083333,0.0,1.000000,1.000000,1.0,2.666667,3.250000,7.000000,8.624242,10.884848,24.0,34.666667,37.750000,289.0,340.333333,374.000000,19.288322,13.109281,11.342525,0.058824,0.094734,0.101577,0.291667,0.239021,0.211181,31.0,23.666667,23.250000,43.0,36.666667,35.250000,6.325581,5.715194,5.778331,5.687369,-3.404298,-2.228197,0.720930,0.644120,0.660509,14.571429,12.414719,13.561039,0.0,0.0,0.0,1.000000,0.872727,0.862879,3.428571,3.203463,3.027597,0.714286,0.686580,0.764935,0.000000,0.127273,0.137121,52.428571,54.706494,54.488203,1.0,1.666667,1.500000,0.0,0.0,0.0,2.0,1.000000,1.000000,0.0,0.000000,0.000000,7.0,6.000000,5.250000,2.0,1.666667,1.750000,0.0,0.000000,0.250000,0.010339,0.005651,0.011262,0.081655,0.081655,0.081655,2.949576,9.299614,10.083837,1.117356,1.049316,1.022744,1.138602,1.010950,0.982661,1.023383,0.970014,0.947172,0.683531,0.714246,0.760530,0.461567,0.323193,0.320465,0.0,5.000000,16.750000,9.0,15.666667,16.250000,20.0,17.666667,15.500000,20.0,24.000000,24.750000,0.0,0.333333,0.750000,1.0,0.666667,0.750000,2.0,2.333333,2.000000,2.0,1.666667,1.750000,0.0,0.333333,0.750000,1.0,1.000000,1.000000,2.0,3.000000,2.500000,4.0,3.333333,3.000000,0.0,0.0,0.0,40.0,40.000000,30.000000,9.0,3.000000,2.250000,0.0,0.000000,0.000000,0.0,19.333333,17.000000,0.0,0.000000,24.000000,4.0,3.333333,2.500000,1.0,0.333333,0.250000,0.0,0.000000,0.000000,0.0,1.333333,1.250000,0.0,0.000000,1.250000,6.0,5.666667,4.250000,1.0,0.333333,0.250000,0.0,0.000000,0.000000,0.0,1.666667,1.500000,0.0,0.000000,1.250000,1.0,1.000000,1.0
5,00-0030506,T.Kelce,2015_06_KC_MIN,88.0,3.5,43.0,4,0,54.0,0.0,10.0,0,0,1,2015,6,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,6.0,8.000000,7.000000,3.0,4.666667,4.800000,32.0,32.000000,36.000000,26.0,43.000000,42.800000,0.0,0.000000,0.400000,-0.507290,-0.014587,3.210175,0.020645,-0.007820,0.060449,0.500000,0.586580,0.711948,5.333333,4.153968,5.465714,5.333333,4.011544,5.380260,8.666667,9.088889,8.903333,0.000000,0.000000,0.066667,0.0,0.666667,0.800000,2.0,2.333333,3.000000,5.833333,6.702020,9.874545,47.0,35.333333,39.600000,343.0,304.000000,367.800000,5.429435,13.986109,10.159907,0.093294,0.106658,0.099921,0.127660,0.244537,0.194477,16.0,23.666667,21.800000,30.0,38.333333,34.200000,6.266667,6.297416,5.875998,-14.737180,-6.193867,-4.729993,0.533333,0.608564,0.635074,12.000000,12.281385,13.248831,0.0,0.0,0.0,0.833333,0.883838,0.856970,2.500000,3.036797,2.922078,0.500000,0.586580,0.711948,0.000000,0.060606,0.109697,52.666667,53.395382,54.123896,1.0,1.666667,1.400000,0.0,0.0,0.0,2.0,1.666667,1.200000,0.0,0.000000,0.000000,5.0,7.666667,5.200000,1.0,1.333333,1.600000,1.0,0.333333,0.400000,0.019256,0.011380,0.012861,0.081655,0.081655,0.081655,6.658328,8.017734,9.398735,0.887306,0.996983,0.995657,0.895504,0.987043,0.965230,0.924629,0.976664,0.942664,1.184936,0.894636,0.845412,1.309650,0.785187,0.518302,4.0,1.333333,14.200000,31.0,26.000000,19.200000,0.0,16.000000,12.400000,0.0,11.333333,19.800000,1.0,0.333333,0.800000,2.0,1.333333,1.000000,0.0,2.000000,1.600000,0.0,1.000000,1.400000,1.0,0.333333,0.800000,2.0,1.666667,1.200000,2.0,3.000000,2.400000,1.0,3.000000,2.600000,0.0,0.0,0.0,0.0,40.000000,24.000000,0.0,3.000000,1.800000,0.0,0.000000,0.000000,0.0,0.000000,13.600000,35.0,11.666667,26.200000,0.0,3.333333,2.000000,0.0,0.333333,0.200000,0.0,0.000000,0.000000,0.0,0.000000,1.000000,3.0,1.000000,1.600000,0.0,5.666667,3.400000,0.0,0.333333,0.200000,0.0,0.000000,0.000000,0.0,0.000000,1.200000,6.0,2.000000,2.200000,1.0,1.000000,1.0
6,00-0030506,T.Kelce,2015_07_PIT_KC,73.0,4.0,41.5,2,0,58.0,57.0,7.0,0,0,1,2015,7,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,7.0,6.666667,7.200000,5.0,4.333333,4.600000,48.0,32.333333,34.000000,44.0,37.666667,42.000000,0.0,0.000000,0.000000,5.532877,0.752579,2.013452,0.114041,0.031615,0.053271,0.714286,0.642857,0.654805,6.857143,4.873016,4.903810,6.857143,4.873016,4.818355,8.800000,8.688889,9.063333,0.000000,0.000000,0.000000,1.0,0.333333,0.800000,4.0,2.333333,2.800000,12.571429,8.468254,8.855498,37.0,36.000000,37.600000,339.0,323.666667,340.600000,9.869829,11.529196,10.925422,0.141593,0.097904,0.103818,0.189189,0.202838,0.206782,22.0,23.000000,21.800000,37.0,36.666667,35.400000,9.162162,7.251470,6.514882,-5.149158,-4.732989,-6.019846,0.594595,0.616286,0.612057,2.857143,9.809524,10.420260,0.0,0.0,0.0,0.285714,0.706349,0.747446,3.000000,2.976190,3.022078,0.714286,0.642857,0.654805,0.142857,0.047619,0.104935,75.571429,60.222222,58.471515,0.0,0.666667,1.200000,0.0,0.0,0.0,1.0,1.666667,1.200000,0.0,0.000000,0.000000,6.0,6.000000,5.800000,1.0,1.333333,1.400000,1.0,0.666667,0.400000,0.017382,0.015659,0.010718,0.081655,0.081655,0.081655,11.674759,7.094221,9.246386,0.964612,0.989758,0.999973,0.973701,1.002602,0.980411,0.950674,0.966229,0.957069,0.899382,0.922616,0.845412,0.762520,0.844579,0.608350,0.0,1.333333,3.800000,0.0,13.333333,15.600000,51.0,23.666667,20.800000,37.0,19.000000,21.800000,0.0,0.333333,0.400000,0.0,1.000000,0.800000,4.0,2.000000,2.200000,1.0,1.000000,1.200000,1.0,0.666667,0.600000,0.0,1.000000,1.000000,4.0,2.666667,3.000000,2.0,2.333333,2.600000,0.0,0.0,0.0,88.0,42.666667,41.600000,0.0,3.000000,1.800000,0.0,0.000000,0.000000,0.0,0.000000,11.600000,0.0,11.666667,7.000000,5.0,3.000000,3.000000,0.0,0.333333,0.200000,0.0,0.000000,0.000000,0.0,0.000000,0.800000,0.0,1.000000,0.600000,6.0,4.000000,4.600000,1.0,0.666667,0.400000,0.0,0.000000,0.000000,0.0,0.000000,1.000000,0.0,2.000000,1.200000,1.0,1.000000,1.0
7,00-0030506,T.Kelce,2015_08_DET_KC,49.0,3.0,45.0,2,0,50.0,91.0,2.0,0,0,1,2015,8,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,6.0,6.333333,7.400000,5.0,4.333333,4.800000,67.0,49.000000,42.200000,21.0,30.333333,38.800000,0.0,0.000000,0.000000,5.287598,3.437728,2.155343,0.199176,0.111287,0.057951,0.833333,0.682540,0.661472,11.166667,7.785714,6.097143,11.166667,7.785714,6.011688,4.200000,7.222222,8.053333,0.000000,0.000000,0.000000,1.0,0.666667,0.800000,3.0,3.000000,2.800000,12.166667,10.190476,8.968831,31.0,38.333333,34.800000,201.0,294.333333,290.400000,10.839399,8.712888,12.533511,0.333333,0.189407,0.158980,0.193548,0.170132,0.223270,21.0,19.666667,22.800000,31.0,32.666667,36.600000,6.483871,7.304233,6.907656,3.448312,-5.479342,-4.056489,0.677419,0.601782,0.619541,6.666667,7.174603,9.273593,0.0,0.0,0.0,1.000000,0.706349,0.787446,2.500000,2.666667,2.922078,0.666667,0.626984,0.628139,0.166667,0.103175,0.098268,50.500000,59.579365,57.251515,1.0,0.666667,1.200000,0.0,0.0,0.0,3.0,2.000000,1.800000,0.0,0.000000,0.000000,1.0,4.000000,6.000000,2.0,1.333333,1.400000,1.0,1.000000,0.600000,0.005568,0.014069,0.011418,0.081655,0.081655,0.081655,9.370165,9.234418,9.019626,1.094481,0.982133,1.010009,1.102539,0.990581,1.007474,1.093353,0.989552,0.994804,1.019300,1.034540,0.920518,0.964940,1.012370,0.816604,14.0,6.000000,3.600000,33.0,21.333333,22.200000,0.0,17.000000,19.800000,26.0,21.000000,19.400000,1.0,0.666667,0.400000,3.0,1.666667,1.400000,0.0,1.333333,2.000000,1.0,0.666667,1.000000,1.0,1.000000,0.600000,3.0,1.666667,1.600000,1.0,2.333333,2.800000,1.0,1.333333,2.400000,0.0,0.0,0.0,0.0,29.333333,41.600000,0.0,0.000000,1.800000,0.0,0.000000,0.000000,47.0,15.666667,9.400000,26.0,20.333333,12.200000,0.0,1.666667,3.000000,0.0,0.000000,0.200000,0.0,0.000000,0.000000,3.0,1.000000,0.600000,2.0,1.666667,1.000000,0.0,2.000000,4.600000,0.0,0.333333,0.400000,0.0,0.000000,0.000000,3.0,1.000000,0.600000,3.0,3.000000,1.800000,1.0,1.000000,1.0

In [58]:
# Prosecna statistika za T.Kelce u sezoni 2015
player_id = '00-0030506'
season_year = 2015

kelce_season = (
    df[(df['receiver_player_id'] == player_id) & (df['season'] == season_year)]
    .sort_values('week')
    .copy()
)

print(f"Igrac: {kelce_season['receiver_player_name'].iloc[0]} ({player_id})")
print(f"Sezona: {season_year}")
print(f"Broj utakmica: {len(kelce_season)}")
print(f"Nedelje: {kelce_season['week'].tolist()}")

summary = {
    'games_played': len(kelce_season),
    'targets_total': kelce_season['targets'].sum(),
    'receptions_total': kelce_season['receptions'].sum(),
    'receiving_yards_total': kelce_season['receiving_yards'].sum(),
    'tds_total': kelce_season['tds'].sum(),
    'air_yards_total': kelce_season['air_yards'].sum(),
    'yac_total': kelce_season['yac'].sum(),
    'targets_per_game': kelce_season['targets'].mean(),
    'receptions_per_game': kelce_season['receptions'].mean(),
    'receiving_yards_per_game': kelce_season['receiving_yards'].mean(),
    'tds_per_game': kelce_season['tds'].mean(),
    'air_yards_per_game': kelce_season['air_yards'].mean(),
    'yac_per_game': kelce_season['yac'].mean(),
    'catch_rate_avg': kelce_season['catch_rate'].mean(),
    'yards_per_target_avg': kelce_season['yards_per_target'].mean(),
    'target_share_avg': kelce_season['target_share'].mean(),
    'air_yard_share_avg': kelce_season['air_yard_share'].mean(),
    'epa_avg': kelce_season['epa'].mean(),
    'wpa_avg': kelce_season['wpa'].mean(),
    'adot_avg': kelce_season['adot'].mean(),
}

season_summary = pd.DataFrame(
    {'metric': list(summary.keys()), 'value': list(summary.values())}
)
season_summary['value'] = season_summary['value'].astype(float).round(3)
season_summary

Igrac: T.Kelce (00-0030506)
Sezona: 2015
Broj utakmica: 18
Nedelje: [1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

                      metric     value
0               games_played    18.000
1              targets_total   124.000
2           receptions_total    86.000
3      receiving_yards_total  1026.000
4                  tds_total     5.000
5            air_yards_total   695.000
6                  yac_total   609.000
7           targets_per_game     6.889
8        receptions_per_game     4.778
9   receiving_yards_per_game    57.000
10              tds_per_game     0.278
11        air_yards_per_game    38.611
12              yac_per_game    33.833
13            catch_rate_avg     0.687
14      yards_per_target_avg     8.385
15          target_share_avg     0.202
16        air_yard_share_avg     0.127
17                   epa_avg     1.781
18                   wpa_avg     0.042
19                  adot_avg     6.000

In [7]:
# STEP 10/11/12 — data sufficiency filter, no-history drop, and target transform

model_df_step = model_df.copy()

# STEP 10: keep only player-season groups with at least 6 games
player_season_games = (
    model_df_step.groupby(['receiver_player_id', 'season'])
    .size()
    .rename('games_in_season')
    .reset_index()
)

valid_player_seasons = player_season_games[player_season_games['games_in_season'] >= 6][
    ['receiver_player_id', 'season']
]

rows_before_step10 = len(model_df_step)
model_df_step = model_df_step.merge(valid_player_seasons, on=['receiver_player_id', 'season'], how='inner')
rows_after_step10 = len(model_df_step)

# STEP 11: drop rows with no prior in-season history (all lag1 features are NaN)
lag1_cols = [c for c in model_df_step.columns if c.endswith('_lag1')]
if not lag1_cols:
    raise ValueError('No lag1 columns found. Step 9 must run before Step 11.')

no_history_mask = model_df_step[lag1_cols].isna().all(axis=1)
rows_before_step11 = len(model_df_step)
model_df_step = model_df_step.loc[~no_history_mask].copy()
rows_after_step11 = len(model_df_step)

# STEP 12: log1p target transform for training
# Receiving yards can be negative on some plays, so clip to 0 before log1p.
neg_target_rows = int((model_df_step['receiving_yards'] < 0).sum())
model_df_step['receiving_yards_log'] = np.log1p(model_df_step['receiving_yards'].clip(lower=0))

# Final modeling dataframe for training/evaluation workflow
model_df_final = model_df_step.copy()

print('STEP 10 — Filter player-seasons with >= 6 games')
print(f'Rows before: {rows_before_step10}, rows after: {rows_after_step10}, removed: {rows_before_step10 - rows_after_step10}')
print()
print('STEP 11 — Drop no-history rows (all lag1 are NaN)')
print(f'Rows before: {rows_before_step11}, rows after: {rows_after_step11}, removed: {rows_before_step11 - rows_after_step11}')
print()
print('STEP 12 — Target transform')
print(f'Negative receiving_yards rows clipped to 0 before log1p: {neg_target_rows}')
print('Columns now include receiving_yards_log:', 'receiving_yards_log' in model_df_final.columns)

# Reminder for evaluation: convert predictions back to original yards scale
print('\nFor evaluation use: y_pred = np.expm1(y_pred_log)')
print('All metrics should be computed on receiving_yards scale (original units).')

model_df_final[['receiver_player_id', 'season', 'week', 'receiving_yards', 'receiving_yards_log']].head(15)

STEP 10 — Filter player-seasons with >= 6 games
Rows before: 46115, rows after: 41100, removed: 5015

STEP 11 — Drop no-history rows (all lag1 are NaN)
Rows before: 41100, rows after: 37668, removed: 3432

STEP 12 — Target transform
Negative receiving_yards rows clipped to 0 before log1p: 438
Columns now include receiving_yards_log: True

For evaluation use: y_pred = np.expm1(y_pred_log)
All metrics should be computed on receiving_yards scale (original units).

   receiver_player_id  season  week  receiving_yards  receiving_yards_log
1          00-0020337    2015     2            150.0             5.017280
2          00-0020337    2015     3            186.0             5.231109
3          00-0020337    2015     4             24.0             3.218876
4          00-0020337    2015     6            137.0             4.927254
5          00-0020337    2015     7             78.0             4.369448
6          00-0020337    2015     8             82.0             4.418841
8          00-0020337    2016     2             64.0             4.174387
9          00-0020337    2016     3             87.0             4.477337
10         00-0020337    2016     4            111.0             4.718499
11         00-0020337    2016     5             29.0             3.401197
12         00-0020337    2016     9             47.0             3.871201
13         00-0020337    2016    10             60.0             4.110874
14         00-0020337    2016    11             99.0             4.605170
15         00-0020337    2016    12             20.0             3.044522
16         00-0020337    2016    13             48.0             3.891820

In [8]:
# STEP 13 — strict temporal split by season

train_seasons = list(range(2015, 2022))  # 2015-2021
val_seasons = [2022, 2023]
test_seasons = [2024, 2025]

train_df = model_df_final[model_df_final['season'].isin(train_seasons)].copy()
val_df = model_df_final[model_df_final['season'].isin(val_seasons)].copy()
test_df = model_df_final[model_df_final['season'].isin(test_seasons)].copy()

feature_columns = [
    c for c in model_df_final.columns
    if c not in ['receiver_player_id', 'receiver_player_name', 'game_id', 'receiving_yards', 'receiving_yards_log']
]

print('STEP 13 — TRAIN / VALIDATION / TEST (temporal by season)')
print(f'Train seasons: {train_seasons}')
print(f'Validation seasons: {val_seasons}')
print(f'Test seasons: {test_seasons}')
print()
print(f'Train shape: {train_df.shape}')
print(f'Validation shape: {val_df.shape}')
print(f'Test shape: {test_df.shape}')
print(f'Number of features: {len(feature_columns)}')

# Optional matrices for training
X_train = train_df[feature_columns].copy()
y_train = train_df['receiving_yards_log'].copy()
X_val = val_df[feature_columns].copy()
y_val = val_df['receiving_yards_log'].copy()
X_test = test_df[feature_columns].copy()
y_test = test_df['receiving_yards_log'].copy()

print('\nX/y shapes:')
print(f'X_train: {X_train.shape}, y_train: {y_train.shape}')
print(f'X_val: {X_val.shape}, y_val: {y_val.shape}')
print(f'X_test: {X_test.shape}, y_test: {y_test.shape}')

STEP 13 — TRAIN / VALIDATION / TEST (temporal by season)
Train seasons: [2015, 2016, 2017, 2018, 2019, 2020, 2021]
Validation seasons: [2022, 2023]
Test seasons: [2024, 2025]

Train shape: (25147, 253)
Validation shape: (7680, 253)
Test shape: (4841, 253)
Number of features: 248

X/y shapes:
X_train: (25147, 248), y_train: (25147,)
X_val: (7680, 248), y_val: (7680,)
X_test: (4841, 248), y_test: (4841,)

In [9]:
# Missing values report

def missing_report(name, data, top_n=10):
    miss = data.isna().sum()
    miss = miss[miss > 0].sort_values(ascending=False)
    total_missing = int(miss.sum())
    cols_with_missing = int((data.isna().sum() > 0).sum())
    pct_cells_missing = (total_missing / (data.shape[0] * data.shape[1])) * 100 if data.size else 0

    print(f'=== {name} ===')
    print(f'Shape: {data.shape}')
    print(f'Total missing cells: {total_missing}')
    print(f'Columns with missing: {cols_with_missing}')
    print(f'% missing cells: {pct_cells_missing:.4f}%')

    if len(miss) == 0:
        print('No missing values.')
        print()
        return

    top = miss.head(top_n).to_frame('missing_count')
    top['missing_pct'] = (top['missing_count'] / len(data) * 100).round(3)
    print(f'Top {min(top_n, len(top))} columns with missing:')
    print(top)
    print()

missing_report('df (raw + engineered helper cols)', df)
missing_report('model_df (after Step 5/6/8/9)', model_df)
missing_report('model_df_final (after Step 10/11/12)', model_df_final)
missing_report('X_train', X_train)
missing_report('X_val', X_val)
missing_report('X_test', X_test)

=== df (raw + engineered helper cols) ===
Shape: (46115, 104)
Total missing cells: 0
Columns with missing: 0
% missing cells: 0.0000%
No missing values.

=== model_df (after Step 5/6/8/9) ===
Shape: (46115, 252)
Total missing cells: 1248072
Columns with missing: 228
% missing cells: 10.7398%
Top 10 columns with missing:
                missing_count  missing_pct
targets_lag1             5474        11.87
yards_Q1_roll5           5474        11.87
yards_Q2_roll3           5474        11.87
yards_Q2_roll5           5474        11.87
yards_Q3_lag1            5474        11.87
yards_Q3_roll3           5474        11.87
yards_Q3_roll5           5474        11.87
yards_Q4_lag1            5474        11.87
yards_Q4_roll3           5474        11.87
yards_Q4_roll5           5474        11.87

=== model_df_final (after Step 10/11/12) ===
Shape: (37668, 253)
Total missing cells: 0
Columns with missing: 0
% missing cells: 0.0000%
No missing values.

=== X_train ===
Shape: (25147, 248)
Total missing cells: 0
Columns with missing: 0
% missing cells: 0.0000%
No missing values.

=== X_val ===
Shape: (7680, 248)
Total missing cells: 0
Columns with missing: 0
% missing cells: 0.0000%
No missing values.

=== X_test ===
Shape: (4841, 248)
Total missing cells: 0
Columns with missing: 0
% missing cells: 0.0000%
No missing values.

In [10]:
# STEP 15 — Feature scaling (fit on train only)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit ONLY on training features
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

# Apply the fitted scaler to validation and test
X_val_scaled = pd.DataFrame(
    scaler.transform(X_val),
    columns=X_val.columns,
    index=X_val.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

print('STEP 15 — StandardScaler (fit on train only)')
print(f'X_train_scaled shape: {X_train_scaled.shape}')
print(f'X_val_scaled shape: {X_val_scaled.shape}')
print(f'X_test_scaled shape: {X_test_scaled.shape}')

# Quick sanity checks
train_mean_abs = float(np.abs(X_train_scaled.mean()).mean())
train_std_mean = float(X_train_scaled.std(ddof=0).mean())
print(f'Avg |mean| across train features (should be near 0): {train_mean_abs:.6f}')
print(f'Avg std across train features (should be near 1): {train_std_mean:.6f}')

STEP 15 — StandardScaler (fit on train only)
X_train_scaled shape: (25147, 248)
X_val_scaled shape: (7680, 248)
X_test_scaled shape: (4841, 248)
Avg |mean| across train features (should be near 0): 0.000000
Avg std across train features (should be near 1): 0.959677